import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Multi Steps Form",
    default: "Next Multi Steps Form",
  },
  description: "This is the Multi Steps Form Generated by NextJs",
  metadataBase: new URL(
    "https://www.frontendmentor.io/challenges/multistep-form-YVAnSdqQBJ"
  ),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-body bg-alice-blue antialiased">{children}</body>
    </html>
  );
}
